/**
 * Mapping of 30 Seconds of Knowledge Icons as Font
 */

export const SOK_ICONS = {
	facebook: 'sok-icon-facebook',
	monitor: 'sok-icon-monitor',
	instagram: 'sok-icon-instagram',
	emoji_grin: 'sok-icon-emoji-grin',
	folder: 'sok-icon-folder',
	minus: 'sok-icon-minus',
	plus: 'sok-icon-plus',
	emoji_sad: 'sok-icon-emoji-sad',
	bugs: 'sok-icon-bugs',
	emoji_smile: 'sok-icon-emoji-smile',
	paypal: 'sok-icon-paypal',
	settings_1: 'sok-icon-settings-1',
	invoice: 'sok-icon-invoice',
	donation_1: 'sok-icon-donation-1',
	shop_1: 'sok-icon-shop-1',
	chart: 'sok-icon-chart',
	donation_2: 'sok-icon-donation-2',
	copy: 'sok-icon-copy',
	tag: 'sok-icon-tag',
	home: 'sok-icon-home',
	question: 'sok-icon-question',
	arrow_left: 'sok-icon-arrow-left',
	safari: 'sok-icon-safari',
	chrome: 'sok-icon-chrome',
	arrow_down: 'sok-icon-arrow-down',
	twitter: 'sok-icon-twitter',
	power_button: 'sok-icon-power-button',
	emoji_straight: 'sok-icon-emoji-straight',
	emoji_tongue: 'sok-icon-emoji-tongue',
	trash_2: 'sok-icon-trash-2',
	trash_1: 'sok-icon-trash-1',
	emoji_surprise: 'sok-icon-emoji-surprise',
	menu_1: 'sok-icon-menu-1',
	firefox: 'sok-icon-firefox',
	accessibility: 'sok-icon-accessibility',
	qr_code: 'sok-icon-qr-code',
	donation_3: 'sok-icon-donation-3',
	shop_2: 'sok-icon-shop-2',
	chevron_down: 'sok-icon-chevron-down',
	chevron_left: 'sok-icon-chevron-left',
	moon: 'sok-icon-moon',
	save: 'sok-icon-save',
	paste: 'sok-icon-paste',
	dislike: 'sok-icon-dislike',
	chevron_up: 'sok-icon-chevron-up',
	like: 'sok-icon-like',
	bookmark: 'sok-icon-bookmark',
	email: 'sok-icon-email',
	chat: 'sok-icon-chat',
	arrow_up: 'sok-icon-arrow-up',
	menu_2: 'sok-icon-menu-2',
	shop_3: 'sok-icon-shop-3',
	shop_4: 'sok-icon-shop-4',
	bussines: 'sok-icon-bussines',
	settings_2: 'sok-icon-settings-2',
	logo: 'sok-icon-logo',
	browser_shield: 'sok-icon-browser-shield',
	star: 'sok-icon-star',
	cancel: 'sok-icon-cancel',
	shield: 'sok-icon-shield',
	donation_4: 'sok-icon-donation-4',
	camera: 'sok-icon-camera',
	heart: 'sok-icon-heart',
	eye_show: 'sok-icon-eye-show',
	eye_hide: 'sok-icon-eye-hide',
	arrow_right: 'sok-icon-arrow-right',
	open: 'sok-icon-open',
	settings_3: 'sok-icon-settings-3',
	user: 'sok-icon-user',
	linkedin: 'sok-icon-linkedin',
	jobsButton: 'sok-Header-jobsButton'
};

export const SOK_ICONS_LIST = [
	SOK_ICONS.facebook,
	SOK_ICONS.monitor,
	SOK_ICONS.instagram,
	SOK_ICONS.emoji_grin,
	SOK_ICONS.folder,
	SOK_ICONS.minus,
	SOK_ICONS.plus,
	SOK_ICONS.emoji_sad,
	SOK_ICONS.bugs,
	SOK_ICONS.emoji_smile,
	SOK_ICONS.paypal,
	SOK_ICONS.settings_1,
	SOK_ICONS.invoice,
	SOK_ICONS.donation_1,
	SOK_ICONS.shop_1,
	SOK_ICONS.chart,
	SOK_ICONS.donation_2,
	SOK_ICONS.copy,
	SOK_ICONS.tag,
	SOK_ICONS.home,
	SOK_ICONS.question,
	SOK_ICONS.arrow_left,
	SOK_ICONS.safari,
	SOK_ICONS.chrome,
	SOK_ICONS.arrow_down,
	SOK_ICONS.twitter,
	SOK_ICONS.power_button,
	SOK_ICONS.emoji_straight,
	SOK_ICONS.emoji_tongue,
	SOK_ICONS.trash_2,
	SOK_ICONS.trash_1,
	SOK_ICONS.emoji_surprise,
	SOK_ICONS.menu_1,
	SOK_ICONS.firefox,
	SOK_ICONS.accessibility,
	SOK_ICONS.qr_code,
	SOK_ICONS.donation_3,
	SOK_ICONS.shop_2,
	SOK_ICONS.chevron_down,
	SOK_ICONS.chevron_left,
	SOK_ICONS.moon,
	SOK_ICONS.save,
	SOK_ICONS.paste,
	SOK_ICONS.dislike,
	SOK_ICONS.chevron_up,
	SOK_ICONS.like,
	SOK_ICONS.bookmark,
	SOK_ICONS.email,
	SOK_ICONS.chat,
	SOK_ICONS.arrow_up,
	SOK_ICONS.menu_2,
	SOK_ICONS.shop_3,
	SOK_ICONS.shop_4,
	SOK_ICONS.bussines,
	SOK_ICONS.settings_2,
	SOK_ICONS.logo,
	SOK_ICONS.browser_shield,
	SOK_ICONS.star,
	SOK_ICONS.cancel,
	SOK_ICONS.shield,
	SOK_ICONS.donation_4,
	SOK_ICONS.camera,
	SOK_ICONS.heart,
	SOK_ICONS.eye_show,
	SOK_ICONS.eye_hide,
	SOK_ICONS.arrow_right,
	SOK_ICONS.open,
	SOK_ICONS.settings_3,
	SOK_ICONS.user,
	SOK_ICONS.linkedin,
];
