module.exports = {
  ACTIVE_PLATFORM: process.env.TARGET,
  DEVELOPER_WEBSITE_URL: 'https://github.com/petrovicstefanrs',
  WEBSITE_URL: 'https://30secondsofknowledge.com',
  BUGS_URL:
    'https://github.com/petrovicstefanrs/30_seconds_of_knowledge/issues',
  ATTRIBUTIONS_URL:
    'https://github.com/petrovicstefanrs/30_seconds_of_knowledge/blob/master/README.md#attributions',
  DONATION_URL: 'https://www.paypal.me/petrovicstefan/1',
  MERCH_URL: 'https://teespring.com/stores/30-seconds-of-knowledge',
  NEWSLETTER_URL: 'http://eepurl.com/giRHzP',
  THEMES: {
    dark: {
      value: 'dark',
      label: 'Dark (Default)',
    },
    light: {
      value: 'light',
      label: 'Light',
    },
  },
  SNIPPET_LIBRARIES: {
    git: {
      value: 'git',
      label: 'Git',
    },
    javascript: {
      value: 'javascript',
      label: 'Javascript',
    },
    react: {
      value: 'react',
      label: 'React',
    },
    python: {
      value: 'python',
      label: 'Python',
    },
    css: {
      value: 'css',
      label: 'CSS',
    },
    php: {
      value: 'php',
      label: 'PHP',
    },
    dart: {
      value: 'dart',
      label: 'Dart',
    },
    golang: {
      value: 'golang',
      label: 'Go',
    },
    csharp: {
      value: 'csharp',
      label: 'C#',
    },
    ruby: {
      value: 'ruby',
      label: 'Ruby',
    },
    ramda: {
      value: 'ramda',
      label: 'Ramda',
    },
    interview: {
      value: 'interview',
      label: 'Interview Questions',
    },
    // cpp: {
    //   value: 'cpp',
    //   label: 'C++',
    // },
  },
  HIGHLIGHTER_THEMES: {
    'a11y-dark': 'a11y-dark',
    'a11y-light': 'a11y-light',
    agate: 'agate',
    'an-old-hope': 'an-old-hope',
    androidstudio: 'androidstudio',
    'arduino-light': 'arduino-light',
    arta: 'arta',
    ascetic: 'ascetic',
    'atelier-cave-dark': 'atelier-cave-dark',
    'atelier-cave-light': 'atelier-cave-light',
    'atelier-dune-dark': 'atelier-dune-dark',
    'atelier-dune-light': 'atelier-dune-light',
    'atelier-estuary-dark': 'atelier-estuary-dark',
    'atelier-estuary-light': 'atelier-estuary-light',
    'atelier-forest-dark': 'atelier-forest-dark',
    'atelier-forest-light': 'atelier-forest-light',
    'atelier-heath-dark': 'atelier-heath-dark',
    'atelier-heath-light': 'atelier-heath-light',
    'atelier-lakeside-dark': 'atelier-lakeside-dark',
    'atelier-lakeside-light': 'atelier-lakeside-light',
    'atelier-plateau-dark': 'atelier-plateau-dark',
    'atelier-plateau-light': 'atelier-plateau-light',
    'atelier-savanna-dark': 'atelier-savanna-dark',
    'atelier-savanna-light': 'atelier-savanna-light',
    'atelier-seaside-dark': 'atelier-seaside-dark',
    'atelier-seaside-light': 'atelier-seaside-light',
    'atelier-sulphurpool-dark': 'atelier-sulphurpool-dark',
    'atelier-sulphurpool-light': 'atelier-sulphurpool-light',
    'atom-one-dark': 'atom-one-dark',
    'atom-one-dark-reasonable': 'atom-one-dark-reasonable',
    'atom-one-light': 'atom-one-light',
    'brown-paper': 'brown-paper',
    'codepen-embed': 'codepen-embed',
    'color-brewer': 'color-brewer',
    darcula: 'darcula',
    dark: 'dark',
    'default-style': 'default-style',
    docco: 'docco',
    dracula: 'dracula',
    far: 'far',
    foundation: 'foundation',
    github: 'github',
    'github-gist': 'github-gist',
    gml: 'gml',
    googlecode: 'googlecode',
    'gradient-dark': 'gradient-dark',
    'gradient-light': 'gradient-light',
    grayscale: 'grayscale',
    'gruvbox-dark': 'gruvbox-dark',
    'gruvbox-light': 'gruvbox-light',
    hopscotch: 'hopscotch',
    hybrid: 'hybrid',
    idea: 'idea',
    'ir-black': 'ir-black',
    'isbl-editor-dark': 'isbl-editor-dark',
    'isbl-editor-light': 'isbl-editor-light',
    'kimbie.dark': 'kimbie.dark',
    'kimbie.light': 'kimbie.light',
    lightfair: 'lightfair',
    lioshi: 'lioshi',
    magula: 'magula',
    'mono-blue': 'mono-blue',
    monokai: 'monokai',
    'monokai-sublime': 'monokai-sublime',
    'night-owl': 'night-owl',
    nnfx: 'nnfx',
    'nnfx-dark': 'nnfx-dark',
    nord: 'nord',
    obsidian: 'obsidian',
    ocean: 'ocean',
    'paraiso-dark': 'paraiso-dark',
    'paraiso-light': 'paraiso-light',
    pojoaque: 'pojoaque',
    purebasic: 'purebasic',
    qtcreator_dark: 'qtcreator_dark',
    qtcreator_light: 'qtcreator_light',
    railscasts: 'railscasts',
    rainbow: 'rainbow',
    routeros: 'routeros',
    'school-book': 'school-book',
    'shades-of-purple': 'shades-of-purple',
    'solarized-dark': 'solarized-dark',
    'solarized-light': 'solarized-light',
    srcery: 'srcery',
    'stackoverflow-dark': 'stackoverflow-dark',
    'stackoverflow-light': 'stackoverflow-light',
    sunburst: 'sunburst',
    tomorrow: 'tomorrow',
    'tomorrow-night': 'tomorrow-night',
    'tomorrow-night-blue': 'tomorrow-night-blue',
    'tomorrow-night-bright': 'tomorrow-night-bright',
    'tomorrow-night-eighties': 'tomorrow-night-eighties',
    vs: 'vs',
    vs2015: 'vs2015',
    xcode: 'xcode',
    xt256: 'xt256',
    zenburn: 'zenburn',
  },
};
